version: "3.8"
services:
  genny:
    build: .
    container_name: genny
    # image: atemosta/feh-gauntlet-bot:genny-latest
    command: python genny.py
    restart: unless-stopped
    networks:
      - feh-vg-bot
    volumes:
      - ../../assets:/app/assets
networks:
  feh-vg-bot:
    external: true