if: (type = push AND branch IN (master, dev)) OR (type = pull_request AND NOT branch =~ /no-ci/)
  language: python
  python:
    - "3.6.9"      
  install:
    - pip3 install -r requirements.txt
  script:
    - cd Deployment
    - pytest