branches:
  only:
  - master
  - dev
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "3.6.9"      
install:
  - pip3 install -r Deployment/requirements.txt
script:
    - cd Deployment
    - pytest
