version: "3.8"
services:
  convoy:
    build: convoy
    container_name: convoy
    # image: atemosta/feh-gauntlet-bot:convoy-latest
    command: uvicorn api:app --host 0.0.0.0 --port 5057 --reload
    networks:
      - feh-compose-network
    ports:
      - 5057:5057
    volumes:
      - ./assets:/app/assets
  genny:
    build: discord/genny
    container_name: genny
    # image: atemosta/feh-gauntlet-bot:genny-latest
    command: python genny.py
    depends_on:
      - convoy
    networks:
      - feh-compose-network
    ports:
      - 4545:4545
    volumes:
      - ./assets:/app/assets
  rebecca:
    build: discord/rebecca
    container_name: rebecca
    # image: atemosta/feh-gauntlet-bot:rebecca-latest
    command: python rebecca.py
    depends_on:
      - convoy
    networks:
      - feh-compose-network
    ports:
      - 4546:4546
    volumes:
      - ./assets:/app/assets
networks:
  feh-compose-network:
    driver: bridge