version: "3.8"
services:
  robin:
    build: ./
    container_name: robin
    command: go run main.go
    restart: unless-stopped
    networks:
      - feh-vg-bot
    # volumes:
    #   - ../../assets:/app/assets
networks:
  feh-vg-bot:
    external: true